version: '2'
services:
  ico:
    image: jincort/backend-ico-dashboard:develop
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:3000
      - 3000:3000
      - 443:4000
    links:
      - auth
      - redis
      - verify
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
    tty: true

  auth:
    image: jincort/backend-auth:production
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FORCE_HTTPS: disabled
      JWT_KEY: "uZrJ!xe*xN?!;oU.u*;QOSM+|=4C?WH?6eWPcK/6AkIXIVGQguSA*r"
      THROTTLER_WHITE_LIST: "127.0.0.1,10.100.0.2,10.100.0.6"
      TENANT_WHITE_LIST: "127.0.0.1,10.100.0.2,10.100.0.6"
    ports:
      - "3000"
      - "4000"
    links:
      - redis

  redis:
    image: jincort/backend-redis:production
    ports:
      - "6379"
    volumes:
      - ./storage/redis:/data


  verify:
    image: jincort/backend-verify:dev-62b3a0d
    environment:
      REDIS_URL: 'redis://redis:6379'
      THROTTLER_WHITE_LIST: "127.0.0.1,10.100.0.2,10.100.0.6"
    links:
      - auth
      - redis

  mongo:
    image: jincort/backend-mongodb:production
    volumes:
        - ./storage/mongodb:/data/db
    ports:
      - 27017:27017
      - 28017:28017